apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp   # Unique key of the ReplicaSet instance
spec:
  replicas: 2   # 2 Pods should exist at all times.
  selector:
    matchLabels:
      app: webapp
  template: # Template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: tchatua/fleetman-webapp-angular:v1.0

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: queue   # Unique key of the ReplicaSet instance
spec:
  replicas: 2   # 2 Pods should exist at all times.
  selector:
    matchLabels:
      app: queue
  template: # Template for the pods
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: webapp
        image: tchatua/fleetman-queue:v1

