apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: tchatua/fleetman-webapp-angular:release0

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-release-v1.0
  labels:
    app: webapp
    release: v1.0
spec:
  containers:
  - name: webapp
    image: tchatua/fleetman-webapp-angular:v1.0

---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
spec:
  containers:
  - name: queue
    image: tchatua/fleetman-queue:v1
